development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: teamfinder_development
  pool: 5
  username: root
  password: password

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: teamfinder_test
  pool: 5
  username: root
  password: password

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: teamfinder_production
  pool: 5
  username: root
  password: password