development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: sql3.freesqldatabase.com
  database: sql3216872
  pool: 5
  port: 3306
  username: sql3216872
  password: hwbyHI6d71

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: sql3.freesqldatabase.com
  database: sql3216872
  pool: 5
  port: 3306
  username: sql3216872
  password: hwbyHI6d71

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: sql3.freesqldatabase.com
  database: sql3216872
  pool: 5
  port: 3306
  username: sql3216872
  password: hwbyHI6d71